name: wasm-deploy

on:
  push:
    branches: [ main ]

env:
  EM_VERSION: 3.1.74
  EM_CACHE_FOLDER: 'emsdk-cache'
  BUILD_TYPE: Release

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set vcpkg environmental variable
        shell: bash
        run: |
          echo "VCPKG_ROOT=$VCPKG_INSTALLATION_ROOT" >> $GITHUB_ENV

      - name: Setup Cache
        id: cache-system-libraries
        uses: actions/cache@v4
        with:
          path: ${{env.EM_CACHE_FOLDER}}
          key: ${{env.EM_VERSION}}-${{ runner.os }}

      - name: Setup Emscripten
        uses: mymindstorm/setup-emsdk@v14
        with:
          version: ${{env.EM_VERSION}}
          actions-cache-folder: ${{env.EM_CACHE_FOLDER}}

      - name: Build
        run: |
          emcmake cmake -B build-web -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}} &&
          cmake --build build-web --config ${{env.BUILD_TYPE}}

      - name: Test
        working-directory: ${{github.workspace}}/build-web
        run: ctest -C ${{env.BUILD_TYPE}} --verbose

      - name: Output
        run: |
          mkdir public &&
          mv build-web/index.html public/index.html &&
          mv build-web/main.data public/main.data &&
          mv build-web/main.js public/main.js &&
          mv build-web/main.wasm public/main.wasm

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public
